### ISSUE TITLE
Roadmap - Fundamental

### ISSUE THREAD

**Issue by ianhi** [ianhi/colony-counter#2]
- [x] Circles appear on click
   - [x] into a counter 
   - [x] counter is displayed somewhere
- [x] Image upload

**Comment by noahhi** [comment]
- [x] able to delete circles

**Comment by ianhi** [comment]
- [x] get running on ianhi.github.io

**Comment by ianhi** [comment]
now available at https://ianhi.github.io/colony-counter/
