### ISSUE TITLE
Roadmap - The Dream

### ISSUE THREAD

**Issue by ianhi** [ianhi/colony-counter#3]
- [ ] permanent zoomed view with crosshair
   - Like webplotdigitizer has
- [ ] add option to upload final labelled image to an S3 bucket to collect the labelled datasets.

**Comment by ianhi** [comment]
I'd like to have a sense of how many people (if any) use this. So it'd be cool to have some sort of very simple analytics - the kind that aren't invasive of privacy. i.e. just counting the number of visitors or number of files uploaded.
- [ ] simplistic usage statistics

**Comment by ianhi** [comment]
https://medium.com/@ashan.fernando/upload-files-to-aws-s3-using-signed-urls-fa0a0cf489db

**Comment by ianhi** [comment]
- [ ] model that tries to detect automatically to prefill selections, then human can edit results
