### ISSUE TITLE
Roadmap - Nice

### ISSUE THREAD

**Issue by noahhi** [ianhi/colony-counter#4]
**Nice**

- [ ] Simple html/css layout + Explanatory text 
     - should not look horrible
- [ ] crtl-scroll to zoom
     - shift scroll to move left right
     - crtl-scroll to zoom
    - scroll to move up and down
    - maybe make the scroll bars appear somehow?   
- [ ] Customize size and color of the circle
- [ ] Faint outline of circle a la gimp
- [ ] Image download

**Comment by ianhi** [comment]
- [ ] Remove gross border when image and canvas don't align
   - this probably is included in general styling
![image](https://user-images.githubusercontent.com/10111092/79940104-bf3c8d00-842e-11ea-88ae-19b03536aa07.png)

- [x] create favicon

**Comment by ianhi** [comment]
- [ ] allow upload of many images. then easily iterating through labelling them + a final summary screen.

**Comment by ianhi** [comment]
For scroll to zoom I've implemented a reasonable one over in ipysegment: https://github.com/ianhi/ipysegment/blob/9b3c46480b3edd675b181fd4e0b7f59670a88e39/src/widget.ts#L365
